# Site settings
title: UI Toolkit
email: 
description: > # this means to ignore newlines until "baseurl:"
  User interface toolkits are helpful for ensuring consistent quality in your web software products and encouraging rapid prototyping in agile software environments.
baseurl: "/btc-styleguide" # the subpath of your site, e.g. /blog/
url: "http://hackoregon.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
